"""
Build a cyberpunk material set from the existing character materials.

For every material under Assets/Material/Characters whose _MainTex is one of the character
textures, this writes a copy into Assets/Material/Characters/Cyberpunk/ that points at the
matching *_Cyber_CLR map generated by generate_cyberpunk_textures.py, and retints the toon rim
light to that character's neon accent.

Copying the existing materials rather than authoring fresh ones keeps every hand-tuned value
(gloss, metallic, rim amount, shader variant, material parent) exactly as it is — only the
albedo and the rim colour change, so the new set is guaranteed to render like the old one.

The originals are never touched, and the whole thing is idempotent: material GUIDs are derived
from the asset path, so re-running updates the same assets instead of orphaning references.

Usage:  python Tools/generate_cyberpunk_materials.py
"""

import hashlib
import os
import re

from generate_cyberpunk_textures import PALETTES, character_of

ROOT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "com.unity.multiplayer.samples.coop", "Assets",
)
TEX_DIR = os.path.join(ROOT, "Textures", "Characters")
MAT_DIR = os.path.join(ROOT, "Material", "Characters")
OUT_DIR = os.path.join(MAT_DIR, "Cyberpunk")

GUID_RE = re.compile(r"^guid: ([0-9a-f]{32})", re.MULTILINE)
MAINTEX_RE = re.compile(
    r"(- _MainTex:\s*\n\s*m_Texture: \{fileID: \d+, guid: )([0-9a-f]{32})(,)")
NAME_RE = re.compile(r"^(  m_Name: )(.*)$", re.MULTILINE)
RIMCOLOR_RE = re.compile(
    r"^(    - _RimColor: \{r: )[^}]*(\})", re.MULTILINE)

# Which character a material dresses, read off its own name. The texture it happens to sample is
# not a reliable signal: Hair_Archer_Girl.mat points at Tank_Head_Boy_CLR.tga in this project, and
# taking the accent from there would give one Archer an amber rim among cyan ones. Longest/most
# specific token first, so "Imp_Vandal" never matches as plain "Imp".
NAME_TO_CHARACTER = [
    ("VandalImp", "VandalImp"), ("Imp_Vandal", "VandalImp"),
    ("Archer", "Archer"), ("Mage", "Mage"), ("Rogue", "Rogue"), ("Tank", "Tank"),
    ("Boss", "Boss"), ("Imp", "Imp"), ("Hero", "Hero"), ("Enemy", "Enemy"),
]

# Materials the automatic texture lookup can't resolve, as
#   material name -> (material to copy instead, cyber texture relative to Textures/Characters).
# Torso_Mage_Girl.mat is a *variant* of Torso_Imp_Vandal.mat whose albedo was overridden to an
# unrelated Yughues metal texture. Copying it would produce a cyber material parented to a
# non-cyber one, so build it from the plain Mage torso material instead.
MATERIAL_OVERRIDES = {
    "Torso_Mage_Girl": ("Torso_Mage_Boy", "Mage/Mage_Torso_Girl_Cyber_CLR.png"),
}

META_TEMPLATE = """fileFormatVersion: 2
guid: {guid}
NativeFormatImporter:
  externalObjects: {{}}
  mainObjectFileID: 2100000
  userData:
  assetBundleName:
  assetBundleVariant:
"""


def read_guid(meta_path):
    with open(meta_path, "r", encoding="utf-8") as handle:
        match = GUID_RE.search(handle.read())
    return match.group(1) if match else None


def stable_guid(relative_path):
    """Deterministic 32-hex GUID from the asset path, so re-runs keep the same asset identity."""
    return hashlib.md5(("versusd/cyberpunk/" + relative_path).encode()).hexdigest()


def build_texture_map():
    """original texture GUID -> (cyber texture GUID, character name)."""
    mapping = {}
    for filename in os.listdir(TEX_DIR):
        source = os.path.join(TEX_DIR, filename)
        if not os.path.isfile(source) or not filename.lower().endswith((".tga", ".png")):
            continue
        source_meta = source + ".meta"
        if not os.path.exists(source_meta):
            continue

        character = character_of(filename)
        stem = os.path.splitext(filename)[0].replace("_CLR", "")
        cyber_meta = os.path.join(TEX_DIR, character, f"{stem}_Cyber_CLR.png.meta")
        if not os.path.exists(cyber_meta):
            print(f"  ! no cyber map for {filename} (run generate_cyberpunk_textures.py first)")
            continue

        original_guid = read_guid(source_meta)
        cyber_guid = read_guid(cyber_meta)
        if original_guid and cyber_guid:
            mapping[original_guid] = (cyber_guid, character)
    return mapping


def rim_color(character):
    r, g, b = PALETTES[character]["accent"]
    return f"{{r: {r / 255.0:.6g}, g: {g / 255.0:.6g}, b: {b / 255.0:.6g}, a: 1}}"


def source_materials():
    """Every .mat directly under Material/Characters and Material/Characters/Toon."""
    for folder in (MAT_DIR, os.path.join(MAT_DIR, "Toon")):
        if not os.path.isdir(folder):
            continue
        for filename in sorted(os.listdir(folder)):
            if filename.endswith(".mat"):
                yield os.path.join(folder, filename)


def find_material(name):
    for path in source_materials():
        if os.path.splitext(os.path.basename(path))[0] == name:
            return path
    return None


def character_from_material_name(material_name, fallback):
    for token, character in NAME_TO_CHARACTER:
        if token in material_name:
            return character
    return fallback


def write_material(source_path, out_name, cyber_guid, character):
    with open(source_path, "r", encoding="utf-8") as handle:
        text = handle.read()

    text = MAINTEX_RE.sub(lambda m: m.group(1) + cyber_guid + m.group(3), text, count=1)

    # Rename only the Material sub-asset. A .mat authored against a ShaderGraph starts with a
    # MonoBehaviour block that also has an (empty) m_Name, so a plain first-match replace renames
    # that instead and leaves the material itself still called after the original.
    split = text.find("\nMaterial:\n")
    if split < 0:
        raise ValueError(f"{source_path}: no Material block found")
    text = text[:split] + NAME_RE.sub(lambda m: m.group(1) + out_name, text[split:], count=1)
    # The toon shader has no emission input, so the rim light is what carries the neon:
    # tinting it to the character's accent is what makes the silhouette read as "lit".
    if RIMCOLOR_RE.search(text):
        text = RIMCOLOR_RE.sub(lambda m: f"    - _RimColor: {rim_color(character)}", text, count=1)

    out_path = os.path.join(OUT_DIR, out_name + ".mat")
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)

    relative = os.path.relpath(out_path, ROOT).replace("\\", "/")
    with open(out_path + ".meta", "w", encoding="utf-8", newline="\n") as handle:
        handle.write(META_TEMPLATE.format(guid=stable_guid(relative)))


def main():
    textures = build_texture_map()
    print(f"{len(textures)} character textures have a cyberpunk counterpart\n")

    os.makedirs(OUT_DIR, exist_ok=True)
    written = 0
    skipped = []

    for path in source_materials():
        base = os.path.splitext(os.path.basename(path))[0]
        name = f"{base}_Cyber"

        if base in MATERIAL_OVERRIDES:
            template_name, texture_relative = MATERIAL_OVERRIDES[base]
            template = find_material(template_name)
            meta = os.path.join(TEX_DIR, texture_relative + ".meta")
            if template is None or not os.path.exists(meta):
                skipped.append(f"{base} (override target missing)")
                continue
            cyber_guid = read_guid(meta)
            texture_character = texture_relative.split("/")[0]
            source_label = f"{os.path.basename(template)} + {texture_relative}"
        else:
            with open(path, "r", encoding="utf-8") as handle:
                match = MAINTEX_RE.search(handle.read())
            if not match or match.group(2) not in textures:
                skipped.append(os.path.basename(path))
                continue
            cyber_guid, texture_character = textures[match.group(2)]
            template = path
            source_label = os.path.basename(path)

        character = character_from_material_name(base, texture_character)
        write_material(template, name, cyber_guid, character)

        print(f"{source_label:38s} -> Cyberpunk/{name}.mat  ({character})")
        written += 1

    print(f"\n{written} materials written to {OUT_DIR}")
    if skipped:
        print(f"skipped (no character texture as _MainTex): {', '.join(skipped)}")


if __name__ == "__main__":
    main()
